name: Pre PR Checks
on: push
jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Src
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
            node_version: 16.20.2
      - name: Install NPM Deps
        run: npm install --also=dev
      - name: ESlint Check
        run: npm run lint
      - name: Unit Tests
        run: npm run test
